#!/usr/bin/bash

# Modified from https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/libexec/ublue-motd

RPM_OSTREE_STATUS=$(rpm-ostree status --json --booted)
IMAGE_REF_NAME=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split("/")[-1]')
if echo "$RPM_OSTREE_STATUS" | grep -q 'hardened:'; then
    IMAGE_TAG=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0]."container-image-reference" // empty | split(":")[-1]')
else
    IMAGE_TAG='ERROR-IMAGE-TAG-MISSING'
fi
TIP=""

IMAGE_DATE=$(echo "$RPM_OSTREE_STATUS" | jq -r '.deployments[0].timestamp')
CURRENT_SECONDS=$(date +%s)
DIFFERENCE=$((CURRENT_SECONDS - IMAGE_DATE))
WEEK=$((7 * 24 * 60 * 60))


if [ "$IMAGE_TAG" == 'ERROR-IMAGE-TAG-MISSING' ]; then
    TIP='**You are missing an image tag, which is unsupported by secureblue. Rebase to the `latest` tag to ensure you continue to receive updates.**'
elif [ "$IMAGE_TAG" != "latest" ]; then
    TIP='**You are on a specific tag, which is unsupported by secureblue. Rebase to the `latest` tag to ensure you continue to receive updates.**'
elif [ "$DIFFERENCE" -ge "$WEEK" ]; then
    TIP='**Your current image is over 1 week old, run `rpm-ostree upgrade`.**'
else
    TIP='**For secureblue release notifications,** [subscribe:](https://secureblue.dev/faq#releases)'
fi
sed -e "s/%IMAGE_REF_NAME%/$IMAGE_REF_NAME/g" -e "s|%TIP%|$TIP|g" /usr/share/ublue-os/motd/secureblue.md | tr '~' '\n' | { command -v glow >/dev/null 2>&1 && glow -s auto -w 78 - || cat; }


